-- AlterTable
ALTER TABLE "Campaign" ADD COLUMN IF NOT EXISTS "companyName" TEXT,
ADD COLUMN IF NOT EXISTS "identifier" TEXT,
ADD COLUMN IF NOT EXISTS "managerCode" TEXT,
ADD COLUMN IF NOT EXISTS "campaignUrl" TEXT,
ADD COLUMN IF NOT EXISTS "campaignType" TEXT DEFAULT 'PUBLIC',
ADD COLUMN IF NOT EXISTS "shortDescription" TEXT,
ADD COLUMN IF NOT EXISTS "logoUrl" TEXT,
ADD COLUMN IF NOT EXISTS "bannerUrl" TEXT,
ADD COLUMN IF NOT EXISTS "allowedUserTypes" TEXT,
ADD COLUMN IF NOT EXISTS "acceptedPlatforms" TEXT,
ADD COLUMN IF NOT EXISTS "discordServerId" TEXT,
ADD COLUMN IF NOT EXISTS "discordRoleId" TEXT,
ADD COLUMN IF NOT EXISTS "discordInviteLink" TEXT,
ADD COLUMN IF NOT EXISTS "startDate" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "endDate" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "contentGuidelines" TEXT,
ADD COLUMN IF NOT EXISTS "campaignRules" TEXT,
ADD COLUMN IF NOT EXISTS "requiredHashtags" TEXT,
ADD COLUMN IF NOT EXISTS "bannedHashtags" TEXT,
ADD COLUMN IF NOT EXISTS "maxContentAgeHours" INTEGER,
ADD COLUMN IF NOT EXISTS "targetSubmissions" INTEGER,
ADD COLUMN IF NOT EXISTS "payoutPerLink" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "totalBudget" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "payoutType" TEXT,
ADD COLUMN IF NOT EXISTS "minViewsForPayout" INTEGER,
ADD COLUMN IF NOT EXISTS "minViewsPerClip" INTEGER,
ADD COLUMN IF NOT EXISTS "maxPayoutPerCreator" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "dailyBudgetLimit" DOUBLE PRECISION;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Campaign_campaignType_idx" ON "Campaign"("campaignType");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "Campaign_identifier_key" ON "Campaign"("identifier") WHERE "identifier" IS NOT NULL;

